<a href="https://colab.research.google.com/github/sonalmahawar/banking_customers-using-ann/blob/main/Banking_customers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Artificial Neural Network**

 Importing the libaries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score

Part 1 Importing the dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
dataset = pd.read_csv("/content/drive/MyDrive/Churn_Modelling.csv")
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

Preprocessing the dataset

In [ ]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


Encoding categorical data


In [ ]:
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2]) 

In [ ]:
print(x)

[[1.0 0.0 0 ... 1 1 101348.88]
 [0.0 0.0 1 ... 0 1 112542.58]
 [1.0 0.0 0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0 ... 0 1 42085.58]
 [0.0 1.0 0 ... 1 0 92888.52]
 [1.0 0.0 0 ... 1 0 38190.78]]


In [ ]:
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


Splitting into testing and training

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

Feature Scaling

In [ ]:
sc = StandardScaler()

In [ ]:
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

Part 2 Building the ANN

Initialize the ANN

In [ ]:
ann = tf.keras.models.Sequential()


Adding the  input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation= 'relu'))

Adding the second hidden layer


In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation= 'relu'))

Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 1, activation= 'sigmoid'))

PART3 Training the ANN

Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy' , metrics = ['accuracy'])

Training the ANN on training set

In [ ]:
ann.fit(x_train, y_train, batch_size = 28, epochs = 100 )

Epoch 1/100
286/286 [==============================] - 0s 1ms/step - loss: 0.3472 - accuracy: 0.8575
Epoch 2/100
286/286 [==============================] - 0s 1ms/step - loss: 0.3462 - accuracy: 0.8571
Epoch 3/100
286/286 [==============================] - 0s 1ms/step - loss: 0.3460 - accuracy: 0.8575
Epoch 4/100
286/286 [==============================] - 0s 1ms/step - loss: 0.3458 - accuracy: 0.8581
Epoch 5/100
286/286 [==============================] - 0s 1ms/step - loss: 0.3453 - accuracy: 0.8589
Epoch 6/100
286/286 [==============================] - 0s 1ms/step - loss: 0.3445 - accuracy: 0.8586
Epoch 7/100
286/286 [==============================] - 0s 1ms/step - loss: 0.3443 - accuracy: 0.8585
Epoch 8/100
286/286 [==============================] - 0s 1ms/step - loss: 0.3440 - accuracy: 0.8591
Epoch 9/100
286/286 [==============================] - 0s 1ms/step - loss: 0.3437 - accuracy: 0.8606
Epoch 10/100
286/286 [==============================] - 0s 1ms/step - loss: 0.3431 - accura

Part 4 - Making the predictions and evaluating the model

Predicting the Test set results

In [ ]:
y_pred = ann.predict(x_test)
y_pred = (y_pred >0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making the Confusion Matrix

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1533   62]
 [ 205  200]]


0.8665